services:
  app:
    build:
      context: .
      args:
        rails_env: development
        bundle_without: ''
        skip_precompile: 'true'
    image: ghcr.io/suwyn/turbo-chat:dev
    volumes:
      - .:/home/appuser/src
    ports:
      - "3000:3000"
    user: 1000:1000
    tty: true
    stdin_open: true
    command: ["./bin/dev"]
